apiVersion: v1alpha1
kind: Setting
metadata:
  name: theme-webstack-setting
spec:
  forms:
    - group: basics
      label: 基础
      formSchema:
        - $formkit: text
          name: siteTitle
          label: 站点标题
          placeholder: 请输入站点标题
          value: 左耳
        - $formkit: text
          name: subTitle
          label: 站点副标题
          placeholder: 请输入站点标题
          value: 导航
    
